#pragma once

#ifndef CE_CUBE_ENABLE_RF24
#define CE_CUBE_ENABLE_RF24 1
#endif

#ifndef CE_CUBE_ENABLE_PRESSURE
#define CE_CUBE_ENABLE_PRESSURE 1
#endif

#ifndef CE_CUBE_ENABLE_PROTOCOL_INFO
#define CE_CUBE_ENABLE_PROTOCOL_INFO 0
#endif

#ifndef CE_CUBE_ENABLE_LEGACY_V1_COMMANDS
#define CE_CUBE_ENABLE_LEGACY_V1_COMMANDS 1
#endif

#ifndef CE_CUBE_ENABLE_CURRENT
#define CE_CUBE_ENABLE_CURRENT 1
#endif

#ifndef CE_CUBE_ENABLE_REPLENISH
#define CE_CUBE_ENABLE_REPLENISH 1
#endif
